# Development Configuration Profile
# For local development and testing

bot:
  name: "Potato Trading Bot"
  version: "0.1.0"
  environment: "dev"

logging:
  log_dir: "logs"
  log_level: "DEBUG"
  console_level: "DEBUG"
  enable_json: false  # Human-readable for dev
  enable_colors: true
  rotation_when: "midnight"
  rotation_interval: 1
  backup_count: 7  # Keep 7 days in dev

exchange:
  name: "binance"
  api_key: "${BINANCE_API_KEY}"
  api_secret: "${BINANCE_API_SECRET}"
  testnet: true  # Always use testnet in dev
  timeout: 30
  rate_limit_per_second: 10

risk:
  max_position_size_pct: 0.02  # 2% per trade (conservative in dev)
  max_total_exposure_pct: 0.20  # 20% total
  max_daily_loss_pct: 0.01  # 1% daily loss limit
  max_slippage_pct: 0.005  # 0.5% max slippage
  min_liquidity_ratio: 0.01  # Position < 1% of daily volume
  var_confidence: 0.95
  enable_emergency_stop: true
