# Production Configuration Profile
# For live trading with real money - USE WITH EXTREME CAUTION

bot:
  name: "Potato Trading Bot"
  version: "0.1.0"
  environment: "prod"

logging:
  log_dir: "logs"
  log_level: "INFO"
  console_level: "WARNING"  # Less verbose in prod
  enable_json: true  # Structured logs for production
  enable_colors: false  # No colors in prod logs
  rotation_when: "midnight"
  rotation_interval: 1
  backup_count: 90  # Keep 90 days in production

exchange:
  name: "binance"
  api_key: "${BINANCE_API_KEY}"
  api_secret: "${BINANCE_API_SECRET}"
  testnet: false  # LIVE TRADING - REAL MONEY
  timeout: 30
  rate_limit_per_second: 8  # More conservative in prod

risk:
  max_position_size_pct: 0.03  # 3% per trade
  max_total_exposure_pct: 0.25  # 25% total
  max_daily_loss_pct: 0.02  # 2% daily loss limit
  max_slippage_pct: 0.005  # 0.5% max slippage
  min_liquidity_ratio: 0.01
  var_confidence: 0.95
  enable_emergency_stop: true  # CRITICAL in production
